import { useColorScheme } from 'react-native';

/**
 * JS mirror of the runtime colours in styles/lemniscate.css (generated by `pnpm tokens`), for
 * native props that cannot take a className. Kept equal to the stylesheet by test/lib/theme.test.ts.
 */
export const THEME = {
  light: {
    background: '#ffffff',
    primary: '#1c60c1',
    secondary: '#40aad4',
    mutedForeground: '#5f6163',
    ring: '#1c60c1',
  },
  dark: {
    background: '#121821',
    primary: '#3cb6d7',
    secondary: '#242c38',
    mutedForeground: '#98a4b3',
    ring: '#3cb6d7',
  },
} as const;

export type ThemeColors = { [K in keyof (typeof THEME)['light']]: string };

export function useThemeColors(): ThemeColors {
  return THEME[useColorScheme() === 'dark' ? 'dark' : 'light'];
}
