import { readFileSync } from 'fs';
import path from 'path';

// styles/lemniscate.css is generated by `pnpm tokens`; its colour values are proven equal to the tokens
// by the root src/test/lemniscate-tokens.test.ts. This file checks the NativeWind/react-native-css shape.
const css = readFileSync(path.join(__dirname, '../styles/lemniscate.css'), 'utf8');

/** Returns the text inside the first `{…}` block that follows `marker`. */
export function block(source: string, marker: string): string {
  const start = source.indexOf(marker);
  if (start < 0) throw new Error(`marker not found: ${marker}`);
  const open = source.indexOf('{', start);
  let depth = 0;
  for (let i = open; i < source.length; i++) {
    if (source[i] === '{') depth++;
    if (source[i] === '}' && --depth === 0) return source.slice(open + 1, i);
  }
  throw new Error(`unclosed block: ${marker}`);
}

export function vars(text: string): Record<string, string> {
  return Object.fromEntries(
    [...text.matchAll(/--([\w-]+):\s*([^;]+);/g)].map((m) => [m[1], m[2].trim()]),
  );
}

// Comments can contain marker-like text (e.g. this file's own header); strip them before
// locating blocks so `block()` always finds the real rule, not a mention inside a comment.
const uncommented = css.replace(/\/\*[\s\S]*?\*\//g, '');

const light = vars(block(uncommented, ':root'));
const dark = vars(block(uncommented, '@media (prefers-color-scheme: dark)'));
const theme = vars(block(uncommented, '@theme inline'));

describe('lemniscate.css', () => {
  it('never uses rem (NativeWind v5 inlines rem as 14px)', () => {
    expect(css).not.toMatch(/\d(\.\d+)?rem\b/);
  });

  it('registers the package source for class scanning', () => {
    expect(css).toContain('@source "../src";');
  });

  // react-native-css 3.0.7 drops static line-heights and multiplies var()/calc() ones by the element
  // font size, so text sizes carry unitless ratios and leading-N divides its px by the font size.
  it.each([
    ['xs', 16, 12], ['sm', 20, 14], ['base', 24, 16], ['lg', 28, 18], ['xl', 28, 20], ['2xl', 32, 24],
    ['3xl', 36, 30], ['4xl', 40, 36], ['5xl', 48, 48], ['6xl', 60, 60], ['7xl', 72, 72], ['8xl', 96, 96],
    ['9xl', 128, 128],
  ] as const)('text-%s line-height is the unitless ratio %spx / %spx', (size, lineHeight, fontSize) => {
    expect(theme[`text-${size}`]).toBe(`${fontSize}px`);
    const ratio = theme[`text-${size}--line-height`];
    expect(ratio).toMatch(/^\d+(\.\d+)?$/);
    expect(Number(ratio) * fontSize).toBeCloseTo(lineHeight, 5);
  });

  it.each([3, 4, 5, 6, 7, 8, 9, 10])('leading-%s is 4px × N divided by the element font size', (n) => {
    const px = n * 4;
    expect(uncommented).toContain(
      `.leading-${n} { --tw-leading: calc(${px} / var(--__rn-css-em)); line-height: calc(${px} / var(--__rn-css-em)); }`,
    );
  });

  it('does not use @utility leading-* (nativewind/theme would win the cascade)', () => {
    expect(uncommented).not.toContain('@utility leading-*');
  });

  it('every --text-*--line-height in @theme inline is unitless (react-native-css multiplies it by font size)', () => {
    const lineHeightVars = Object.entries(theme).filter(([name]) => /^text-.*--line-height$/.test(name));
    expect(lineHeightVars.length).toBeGreaterThan(0);
    lineHeightVars.forEach(([, value]) => {
      expect(value).not.toMatch(/px|rem|em/);
      expect(value).toMatch(/^\d+(\.\d+)?$/);
    });
  });

  it('points every semantic colour at a defined runtime variable', () => {
    const refs = Object.values(theme)
      .map((v) => v.match(/^var\(--([\w-]+)\)$/)?.[1])
      .filter((v): v is string => !!v);
    expect(refs.length).toBeGreaterThan(40);
    refs.forEach((ref) => expect(light[ref]).toBeDefined());
  });

  it('reproduces the repo Tailwind v3 scale in px (radius from the lmns tokens)', () => {
    expect(theme.spacing).toBe('4px');
    expect(theme['radius-sm']).toBe('8px');
    expect(theme['radius-md']).toBe('8px');
    expect(theme['radius-lg']).toBe('10px');
    expect(theme['radius-xl']).toBe('16px');
    expect(theme['text-sm']).toBe('14px');
    expect(theme['text-2xs']).toBe('10px');
    expect(theme['shadow-sm']).toBe('0 1px 2px 0 rgb(0 0 0 / 0.05)');
    expect(theme['font-sans']).toBe('Inter');
    expect(theme['breakpoint-xs']).toBe('480px');
  });
});
